#ifndef MOTIV_CONSTANTS_HPP
#define MOTIV_CONSTANTS_HPP


namespace layers {
    const int Z_LAYER_HIGHLIGHTED_OFFSET = 20;
    const int Z_LAYER_P2P_COMMUNICATIONS = 100;
    const int Z_LAYER_COLLECTIVE_COMMUNICATIONS = 110;
    const int Z_LAYER_SLOTS_MIN_PRIORITY = 10;
    const int Z_LAYER_SLOTS_MAX_PRIORITY = Z_LAYER_SLOTS_MIN_PRIORITY + Z_LAYER_HIGHLIGHTED_OFFSET - 1;
}

#endif //MOTIV_CONSTANTS_HPP
